ALTER TYPE "PurchaseRequestStatus" ADD VALUE IF NOT EXISTS 'NEED_REVISION';
ALTER TYPE "PurchaseRequestStatus" ADD VALUE IF NOT EXISTS 'NEED_CLARIFICATION';

ALTER TYPE "ApprovalAction" ADD VALUE 'REQUESTED_REVISION';
ALTER TYPE "ApprovalAction" ADD VALUE 'REQUESTED_CLARIFICATION';
