ALTER TYPE "PurchaseRequestStatus" ADD VALUE 'NEED_REVISION';
ALTER TYPE "PurchaseRequestStatus" ADD VALUE 'NEED_CLARIFICATION';

ALTER TYPE "ApprovalAction" ADD VALUE 'REQUESTED_REVISION';
ALTER TYPE "ApprovalAction" ADD VALUE 'REQUESTED_CLARIFICATION';
